
#MANAGER VIEWS AVAIALABLE ALL NUMBERS
SELECT * FROM phone_number;
#MANAGAER INSERTS NEW PHONE NUMBERS
INSERT INTO `nexus-carrier`.`phone_number` (`phone_number`) VALUES ('7777772222');
INSERT INTO `nexus-carrier`.`phone_number` (`phone_number`) VALUES ('2126183312');
INSERT INTO `nexus-carrier`.`phone_number` (`phone_number`) VALUES ('2105555556');
INSERT INTO `nexus-carrier`.`phone_number` (`phone_number`) VALUES ('9132223344');

#MANANGER CAN DELETE NUMBER
DELETE FROM `nexus-carrier`.`phone_number` WHERE (`phone_number` = '2102234356');

#MANAGERS CAN VIEW PHONE PLANS
SELECT * FROM phone_plans;

#MANAGERS CAN ADD PHONE PLANS

INSERT INTO phone_plans(plan_name,device_limit,price_per_line,description) VALUE ("SILVER", 2, 30.00, "Talk and Text, 1GB Data");
INSERT INTO phone_plans(plan_name,device_limit,price_per_line,description) VALUE ("BRONZE", 3, 35.00, "Talk and Text, 10 Data");
INSERT INTO phone_plans(plan_name,device_limit,price_per_line,description) VALUE("DIAMOND", 3,50.00,"Unlimited Talk, Text, Data, and Netflix");

#MANAGER CAN REMOVE PLANS
DELETE FROM phone_plans WHERE plan_name = "SILVER"; 
DELETE FROM phone_plans WHERE plan_name = "BRONZE";
DELETE FROM phone_plans WHERE plan_name = "DIAMOND";
UPDATE `nexus-carrier`.`phone_plans` SET `plan_name` = 'Gold Family' WHERE (`plan_name` = 'Gold');

#MANAGER CAN UPDATE PLANS
UPDATE phone_plans SET plan_name = 'Gold Ulta' WHERE( plan_name = 'Gold Family');

#MANAGERS CAN INCREASE PRICES FOR A CERTAIN PLAN
UPDATE phone_plans SET price_per_line = 35.99 WHERE( plan_name = 'Basic Family');

#MANAGER CAN ADD DEVICE MODELS
INSERT INTO device_model(device_name,year,processor,description) VALUE ("HTC Desire 22 Pro", 2021, "SnapDragon 690 5G", "128GB storage, microSDX");
INSERT INTO device_model(device_name,year,processor,description) VALUE ("Apple iPhone13", 2021, "Apple A15 Bionic", "128GB/256GB/1TB storage, no card slot");
INSERT INTO device_model(device_name,year,processor,description) VALUE ("Google Pixel 5a", 2021, "SnapDragon 765G", "128GB storage, no card slot");
INSERT INTO device_model(device_name,year,processor,description) VALUE ("Galaxy S6", 2019, "SuperProcessor 5gz", "Sleek Profile, Dual Camera");

#MANGER CAN DELETE DEVICE MODELS
DELETE FROM device_model WHERE device_name = "HTC Desire 22 Pro";

#MANAGER CAN UPDATE DEVICES (EXAMPLE YEAR)
UPDATE device_model SET year = 1999 WHERE device_name = "Apple iPhone13";
select * from device_model;

#---------------FROM USER PERSPECTIVE------------------#

#USER CREATES THIER ACCOUNT // will not allow duplicate user name
INSERT INTO account(first_name,last_name,user_name,password,email_add ) VALUE("David","Perez","David99","1234","dperez@skillstorm");
INSERT INTO account(first_name,last_name,user_name,password,email_add ) VALUE("Regine","Donatien","Regine88","ABCD","Rdonatien@skillstorm");
INSERT INTO account(first_name,last_name,user_name,password,email_add ) VALUE("Paul","Lee","PaulLee77","23FD","plee@skillstorm");

#USER CAN DELETE THEIR ACCOUNT
DELETE FROM account WHERE user_name = "David99";

#USER CAN UPDATE ACCOUNT (example email)
UPDATE account SET email_add ="Aperez@skillstorm.com" WHERE user_name = "David99";


#USERS CAN SEE AVAIALBE PLANS
SELECT * FROM phone_plans;

# USER ADDED his plan # can only add from plans in phone_plan table. if not , error
INSERT INTO user_plan(user_name_u,plan_name_u,num_of_lines) VALUE ("David99", "Basic Family", 3);
INSERT INTO user_plan(user_name_u,plan_name_u,num_of_lines) VALUE ("Regine88", "Gold Ulta", 3);
INSERT INTO user_plan(user_name_u,plan_name_u,num_of_lines) VALUE ("PaulLee77", "Premium", 3);

### DEVELPER CHECK WE CAN SEE USERS AND ASSOICATED PLANS
SELECT *
FROM account
INNER JOIN user_plan
WHERE user_name_u = user_name;

#USER CAN DELETE PLAN // user id is autogenerated
DELETE FROM user_plan WHERE iduser_plan = 12345679;

#USER CAN UPDATE PLAN
UPDATE user_plan SET plan_name_u = "Premium" WHERE  iduser_plan = 12345685;

# USER VIEWS AVIALABE DEVICES
select * from device_model;
#USER SEES DETAIL ON DEVICE
select * from device_model WHERE device_name = "Apple iPhone13";


#USER ADDS A DEVICE TO THIER PLAN
#USER ADD Phone to his plan and adds phone number to it

#SEE TABLE WITH ALL USERPLANS AND USER DEVICES
SELECT *
FROM user_plan p
INNER JOIN user_device d
ON p.iduser_plan = d.plan_id_d;
select * from user_device;

#add device to plan and phonenumber;
INSERT INTO user_device(device_name_d, phone_number_d,plan_id_d,user_device_first_name,user_device_last_name) 
Value("Apple iPhone13", 9993134456,'12345683',"Paul","Lee");

INSERT INTO user_device(device_name_d, phone_number_d,plan_id_d,user_device_first_name,user_device_last_name) 
Value("Google Pixel 5a", 9991112232,'12345683',"Robert","Lee");

#CHANGE PHONE NUMBER ON A DEVICE by iduser_device
UPDATE user_device SET phone_number_d =9569269082 WHERE iduser_device =1102039424;

#WONT LET YOU CHNAGE TO A NUMBER ALREADY IN USE (EXAMPLE)
## UPDATE user_device SET phone_number_d =9132223344 WHERE iduser_device =1102039424;

#USER IS ABLE TO DELETE A LINE
DELETE FROM user_device WHERE iduser_device = 1102039424;

#HIGH LEVEL DASHBOARDS
#USER CAN SEE ALL PLANS UNDER THIER ACCOUNT
SELECT *
FROM account
INNER JOIN user_plan
ON account.user_name=user_plan.user_name_u
WHERE account.user_name="David99";

#returns all devices attached to that user id
SELECT *
FROM user_plan
INNER JOIN user_device
ON user_plan.iduser_plan = user_device.plan_id_d
WHERE user_device.plan_id_d="12345685";














#FOR MANAGMENT DASHBOARD

###----------OTHER DASHBOARDS FOR MANAGMENT---------------
#RETURNS USERS NAMES THAT HAVE PREMIUM ACCOUTNS
SELECT first_name, last_name, user_plan.plan_name_u
FROM account
INNER JOIN user_plan
ON account.user_name=user_plan.user_name_u
WHERE user_plan.plan_name_u = "Premium";

